name: react_jax
channels:
  - pytorch
  - defaults
dependencies:
  - astroid=2.14.2
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - colorama=0.4.6
  - dill=0.3.7
  - filelock=3.9.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - isort=5.9.3
  - jinja2=3.1.2
  - lazy-object-proxy=1.6.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - mccabe=0.7.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.1
  - openssl=3.0.10
  - pip=23.2.1
  - platformdirs=3.10.0
  - pylint=2.16.2
  - python=3.10.12
  - pytorch=2.0.1
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tk=8.6.12
  - tomli=2.0.1
  - tomlkit=0.11.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - wheel=0.38.4
  - wrapt=1.14.1
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - anyio==4.0.0
      - appdirs==1.4.4
      - appnope==0.1.3
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-record==0.4.1
      - arrow==1.2.3
      - asttokens==2.4.0
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - chex==0.1.82
      - click==8.1.7
      - comm==0.1.4
      - contourpy==1.1.0
      - cycler==0.11.0
      - datasets==2.14.5
      - debugpy==1.6.7.post1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - equinox==0.10.11
      - etils==1.4.1
      - exceptiongroup==1.1.3
      - executing==1.2.0
      - fastjsonschema==2.18.0
      - fonttools==4.42.1
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gitdb==4.0.10
      - gitpython==3.1.34
      - googleapis-common-protos==1.60.0
      - huggingface-hub==0.16.4
      - idna==3.4
      - importlib-resources==6.0.1
      - ipykernel==6.25.2
      - ipython==8.15.0
      - isoduration==20.11.0
      - jax==0.4.14
      - jaxlib==0.4.14
      - jaxtyping==0.2.21
      - jedi==0.19.0
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.1
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.5
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - kiwisolver==1.4.5
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mistune==3.0.1
      - ml-dtypes==0.2.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - nbclient==0.8.0
      - nbconvert==7.8.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.7
      - notebook-shim==0.2.3
      - numpy==1.25.2
      - opt-einsum==3.3.0
      - optax==0.1.7
      - overrides==7.4.0
      - packaging==23.1
      - pandas==2.1.0
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - prometheus-client==0.17.1
      - promise==2.3
      - prompt-toolkit==3.0.39
      - protobuf==3.20.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==13.0.0
      - pycparser==2.21
      - pygments==2.16.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - referencing==0.30.2
      - regex==2023.8.8
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.2
      - safetensors==0.3.3
      - scipy==1.11.2
      - send2trash==1.8.2
      - sentry-sdk==1.30.0
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.2
      - tensorflow-metadata==1.14.0
      - termcolor==2.3.0
      - terminado==0.17.1
      - tfds-nightly==4.9.2.dev202309080044
      - tinycss2==1.2.1
      - tokenizers==0.13.3
      - toml==0.10.2
      - toolz==0.12.0
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.9.0
      - transformers==4.33.2
      - typeguard==4.1.3
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==2.0.4
      - wandb==0.15.9
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.2
      - xxhash==3.3.0
      - yarl==1.9.2
      - zipp==3.16.2